### ISSUE TITLE
Images do not render from Content Hub DAM

### ISSUE THREAD

**Issue by rkuchler** [blipson89/Synthesis#93] opened 2021-05-21 15:13 UTC
**Do you want to request a *feature* or report a *bug*?**
This appears to be a bug.

**What is the current behavior?**
When calling either the Render method or the ImageFor method on an ImageField object the image files to render if it is sourced from the DAM.  

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install and configure the Sitecore Connect™ for Sitecore DAM 2.0 module in a Sitecore 9.3 XP solution
2. Add an image field to any template
3. Create an item based on that template
3. In the content editor edit that item and click on the Browse Sitecore DAM link to add an image 
4. Preview the item and note that the image does not render

**What is the expected behavior?**
The image would render the same way it would if it were sourced from the media library 

**Please mention your Sitecore version and Synthesis version.**
Sitecore 9.3
Synthesis 9.1.0.2

**Comment by blipson89** [comment] 2021-06-10 01:07
Fixed in Synthesis 9.1.2

Thank you for the help @rkuchler

**Comment by jroho** [comment] 2021-07-24 05:04
**Do you want to request a feature or report a bug?**
I think this issue needs to be reopened.

**What is the current behavior?**
This issue appears to persist when accessing Url from ContentHubImageField which in is derived from IImageField and FileField. I followed the instructions to implement ContentHubImageField, but there appears to be issues accessing Url, which is inherited  from Synthesis.FieldTypes.Interfaces.IFileField, and IImageField. It's always null for images set from Content Hub. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install and configure the Sitecore Connect™ for Sitecore DAM 2.0 module in a Sitecore 9.3 XP solution
2. Add an image field to any template
3. Create an item based on that template
4. In the content editor edit that item and click on the Browse Sitecore DAM link to add an image
5. Preview the item and note that the image does not render
6. Url property is always null for the ContentHubImageField (We don't use Render() or ImageFor as we have a custom library that inherits from IImageField)

**What is the expected behavior?**
I would expect to be able to access data member, Url, from ContentHubImageField, derived from IImageField .. IFileField. I also added IsContentHub property to the IContentHubImageField interface. This property is useful when exposed here.

My pr does solve the issue for us (we are fully integrated with content hub), if you want to take a look: #97 

**Please mention your Sitecore version and Synthesis version.**
Sitecore 9.3
Synthesis 9.1.0.2

**Comment by jroho** [comment] 2021-07-24 05:14
**Do you want to request a feature or report a bug?**
I think this issue needs to be reopened.

**What is the current behavior?**
This issue appears to persist when accessing Url from ContentHubImageField which is derived from IImageField :: FileField. I followed the instructions to implement ContentHubImageField, but there appears to be issues accessing Url, which is inherited from Synthesis.FieldTypes.Interfaces.IFileField, and IImageField. It's always null for images set from Content Hub.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install and configure the Sitecore Connect™ for Sitecore DAM 2.0 module in a Sitecore 9.3 XP solution
2. Add an image field to any template
3. Create an item based on that template
4. In the content editor edit that item and click on the Browse Sitecore DAM link to add an image
5. Preview the item and note that the image does not render
6. Url property is always null for the ContentHubImageField (We don't use Render() or ImageFor() as we have a custom library that inherits from IImageField)

**What is the expected behavior?**
I would expect to be able to access data member, Url, from ContentHubImageField, derived from IImageField :: IFileField. I also added IsContentHub property to the IContentHubImageField interface. This property is useful when exposed here.

My pr does solve the issue for us (we are fully integrated with content hub), if you want to take a look: #97

**Please mention your Sitecore version and Synthesis version.**
Sitecore 9.3
Synthesis 9.1.0.2

**Comment by blipson89** [comment] 2022-04-23 15:06
Hi @jroho,

It looks like a potential fix was released a while ago but I forgot to follow up. Is this issue resolved?

Thanks,
Ben

**Comment by jroho** [comment] 2022-10-11 08:07
Hey Ben,

Yep, already using it on a newer project. Working as intendended without
the need to override your dll.

Thanks,
Jesse

**Comment by blipson89** [comment] 2022-10-11 21:08
Glad to hear it! I'm going to close this issue out then.

**Closed by blipson89** 2022-10-11 21:08 UTC
